services:
  web:
    container_name: demo-django-devops
    image: demo-django-devops:latest
    ports:
      - 8001:8000
    build:
      context: .
      target: develop

  web-production:
    container_name: demo-django-devops
    image: docker.io/polirritmico/demo-django-devops:latest
    ports:
      - 8001:8000
    profiles:
      - production
